export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const DOWNLOAD_INGREDIENTS = "DOWNLOAD_INGREDIENTS";
export const DO_DOWNLOAD_INGREDIENTS = "DO_DOWNLOAD_INGREDIENTS";
export const RESET_BURGER_STATE = "RESET_BURGER_STATE";
export const RESET_IS_PURCHASING = "RESET_IS_PURCHASING";
export const SET_PURCHASING = "SET_PURCHASING";

export const PURCHASE_SUCESS = "PURCHASE_SUCESS";
export const PURCHASE_FAIL   = "PURCHASE_FAIL";
export const PURCHASE_START        = "PURCHASE_START";
export const PURCHASE_INIT   = "PURCHASE_INIT";
export const DO_PURCHASE_ORDER = "DO_PURCHASE_ORDER";

export const FETCH_ORDER_INIT = "FETCH_ORDER_INIT";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const SET_ORDERS   = "SET_ORDERS";
export const DO_DOWNLOAD_ORDERS = "DO_DOWNLOAD_ORDERS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT"
export const DO_LOGOUT  = "DO_LOGOUT";
export const DO_LOGIN  = "DO_LOGIN";
export const DO_CHECK_AUTH = "DO_CHECK_AUTH";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
